name: Webgl Map
version: 0.1
description: Displays a 3D render of your server's map in the browser
author: Thinkofdeath

main: think.webglmap.bukkit.WebglMapPlugin

commands:
   webmap:
     description: TODO
     aliases: [webglmap]
     permission: webmap.command
     usage: N/A