name: ThinkMap
version: ${project.version}-${build.number}
description: Displays a 3D render of your server's map in the browser
author: Thinkofdeath

main: uk.co.thinkofdeath.thinkcraft.bukkit.ThinkMapPlugin
load: STARTUP

externalRepos:
 - "https://hub.spigotmc.org/nexus/content/repositories/snapshots"
externalDepend:
 - "io.netty:netty-all:5.0.0.Alpha1"
 - "commons-io:commons-io:2.4"
 - "net.sf.trove4j:trove4j:3.0.3"
 - "com.google.code.gson:gson:2.2.4"

commands:
   thinkmap:
     description: TODO
     aliases: [thinkmap]
     usage: N/A