name: Webgl_Map
version: 0.1
description: Displays a 3D render of your server's map in the browser
author: Thinkofdeath

main: uk.co.thinkofdeath.webglmap.bukkit.WebglMapPlugin
load: STARTUP

commands:
   webmap:
     description: TODO
     aliases: [webglmap]
     permission: webmap.command
     usage: N/A